name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'doc/*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: src/python/environment.yml
          activate-environment: mimicsid
          auto-activate-base: false

      - name: Display Conda info
        run: |
          conda info
          conda list

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Prepare tests
        run: 'make info testdeps'

      - name: Run tests
        run: 'make test'
