name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'doc/*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          channels: conda-forge
          mamba-version: "*"
          channel-priority: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: src/python/environment.yml
          activate-environment: earth-analytics-python

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Prepare tests
        run: 'make info testdeps'

      - name: Run tests
        run: 'make test'
